version: '3'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123456
  grabber:
    build:
      context: .
    image: xgrabber
    restart: always